version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: REgPHX{&|NIa>-#9
      MYSQL_DATABASE: kuroro
      MYSQL_USER: stratzorduser
      MYSQL_PASSWORD: X2}XrF34u?f49CBB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/kuroro?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: stratzorduser
      SPRING_DATASOURCE_PASSWORD: X2}XrF34u?f49CBB
    depends_on:
      - db
    restart: always

volumes:
  db_data: {}
