INSERT INTO move (name, power, category, description) VALUES ('???', 0, 'Status', 'This move raises the users Mystic Defense by one stage.');
INSERT INTO move (name, power, category, description) VALUES ('Acceleration', 0, 'Status', 'This move raises the users Speed by two stages.');
INSERT INTO move (name, power, category, description) VALUES ('Acidic Flux', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Acrid Bite', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Aqua Blast', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Arcane Knowledge', 0, 'Status', 'This move raises the user’s Mystic Attack by one stage.');
INSERT INTO move (name, power, category, description) VALUES ('Armor Up', 0, 'Status', 'This move raises the users Natural Defense by one stage.');
INSERT INTO move (name, power, category, description) VALUES ('Assault Rush', 0, 'Status', 'This move raises the users Natural Attack by two stages.');
INSERT INTO move (name, power, category, description) VALUES ('Axe Kick', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Bark Blast', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Bloomburst', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Bunker Down', 0, 'Status', 'This move raises the users Natural Defense by two stages.');
INSERT INTO move (name, power, category, description) VALUES ('Burning Lash', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Charging Atom', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Beam', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Bolt', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Flame', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Gust', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Iron', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Leaf', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Oxide', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Pulse', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Shadow', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Spell', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Charging Wave', 50, 'Mystic', 'The user’s natural or mystic attack (whichever is higher) is used to calculate the damage this move does and is increased by one stage after using this move. This move doubles in power when hitting a beast of the same element that resists it.');
INSERT INTO move (name, power, category, description) VALUES ('Chemical Crash', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Corrosive Wave', 0, 'Status', 'Target is corroded and loses 1/8 of its max HP every turn. Doesnt work on Corrosion types.');
INSERT INTO move (name, power, category, description) VALUES ('Crashing Waves', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Crosstide', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Dark Harvest', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Dawngrasp', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Degenerate', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Depth Attack', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Electric Storm', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Ferocious Howl', 0, 'Status', 'This move raises the users Natural Attack by one stage.');
INSERT INTO move (name, power, category, description) VALUES ('Ferrous Laser', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Fire Blaze', 0, 'Status', 'Target is burned and losses 1/16 HP every turn. Its natural damage output is halved. Doesnt work on Fire types.');
INSERT INTO move (name, power, category, description) VALUES ('Firebrand', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Fist Barrage', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Flaming Fists', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Flashing Fist', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Geologic Burst', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Glowing Mists', 0, 'Status', 'This move raises the users Mystic Defense by two stages.');
INSERT INTO move (name, power, category, description) VALUES ('Illuminating Beam', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Inferno', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Introspection', 0, 'Status', 'This move raises the users Mystic Attack by two stages.');
INSERT INTO move (name, power, category, description) VALUES ('Iron Slam', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Jungle Healing', 0, 'Status', 'The user’s team is recovered from every status condition.');
INSERT INTO move (name, power, category, description) VALUES ('Lightning Bolt', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Luminescence', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Maddening Scream', 0, 'Status', 'This move reduces the opponent’s natural and mystic attack by one stage. If used on the first turn the beast is in the battle, it gets an increased priority of 1.');
INSERT INTO move (name, power, category, description) VALUES ('Magma Shot', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Mass Abduction', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Meditate', 0, 'Status', 'The user meditates and recovers 50% of its max HP. If used consecutively, the amount of recovery is reduced each turn. A Paralyzed beast cannot concentrate enough and will recover 25% only.');
INSERT INTO move (name, power, category, description) VALUES ('Meditative Strike', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Metal Grinder', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Mystic Veil', 0, 'Mystic', 'The user creates a Veil on its side of the field that reduces the damage taken from mystic moves for 5 turns.');
INSERT INTO move (name, power, category, description) VALUES ('Natural Veil', 0, 'Natural', 'The user creates a Veil on its side of the field that reduces the damage taken from natural moves for 5 turns.');
INSERT INTO move (name, power, category, description) VALUES ('Nature Protection', 0, 'Status', 'The users team is protected against status conditions for five turns.');
INSERT INTO move (name, power, category, description) VALUES ('Nerve Pulse', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Night’s Embrace', 110, 'Mystic', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Oni Slash', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Otherside Embrace', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Paralysis Wave', 0, 'Status', 'Paralyzes the target. Doesnt work on Earth and Electric types. Some mechanics are affected by this move.');
INSERT INTO move (name, power, category, description) VALUES ('Petal Scythe', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Provocation', 0, 'Status', 'The target cannot use status moves for 3 turns ');
INSERT INTO move (name, power, category, description) VALUES ('Quicksand Trap', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Redirection Sign', 0, 'Status', 'The user redirects any move to itself during the turn.');
INSERT INTO move (name, power, category, description) VALUES ('Roundhouse Slam', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Sandstorm', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Seismic Wave', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Shade Slash', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Shadowblade', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Shear Stream', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Shield', 0, 'Status', 'The user is protected from all effects and damage during the turn. Cannot be used consecutively.');
INSERT INTO move (name, power, category, description) VALUES ('Silicon Slashes', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Skyfall', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Sleep Pollen', 0, 'Status', 'Target falls asleep and cannot move while this effect is in play. Doesnt work on Plant types.');
INSERT INTO move (name, power, category, description) VALUES ('Soft Reset', 0, 'Status', 'A mysterious mist affects the entire battle field and resets all stat changes.');
INSERT INTO move (name, power, category, description) VALUES ('Soul Contract', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Spirit Beam', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Spring', 0, 'Status', 'This move raises the users Speed by one stage.');
INSERT INTO move (name, power, category, description) VALUES ('Steel Blast', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Strike Conduit', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Sulfuric Sting', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Sunblade', 100, 'Natural', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Team Help', 0, 'Status', 'This move increases the partners damage by 50% during the turn.');
INSERT INTO move (name, power, category, description) VALUES ('Thicket Thrash', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Thunderous Boom', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Titanic Quake', 110, 'Natural', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Torrential Blast', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Total Eclipse', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Untamed Growth', 110, 'Mystic', 'This move affects adjacent beasts, no secondary effect. Power reduction is applied when hitting more than one target.');
INSERT INTO move (name, power, category, description) VALUES ('Vacuum Slice', 100, 'Mystic', 'This move does damage to the opponent. ');
INSERT INTO move (name, power, category, description) VALUES ('Wind Breaker', 90, 'Mystic', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Wing Frenzy', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
INSERT INTO move (name, power, category, description) VALUES ('Zap Razor', 90, 'Natural', 'This move becomes sequential when used on consecutive turns and increases in power. ');
