INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 182),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 182),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 066),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 066),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 069),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 069),
                                                     (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 057),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 057),
                                                     (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 054),
                                                     (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 054),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 996),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 996),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 102),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 102),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 051),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 051),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 998),
                                                     (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 998),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 167),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 167),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 012),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 012),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 200),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 200),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 063),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 063),
                                                     (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 081),
                                                     (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 081),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 021),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 021),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 093),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 093),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 045),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 045),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 042),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 042),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 990),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 990),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 989),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 989),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 155),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 155),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 129),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 129),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 108),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 108),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 158),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 158),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 025),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 025),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 099),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 099),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 027),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 027),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 018),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 018),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 114),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 114),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 173),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 173),
                                                     (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 023),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 023),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 1000),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 1000),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 060),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 060),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 201),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 201),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 009),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 009),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 014),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 014),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 141),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 141),
                                                     (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 991),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 991),
                                                     (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 016),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 016),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 036),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 036),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 120),
                                                     (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 120),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 072),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 072),
                                                     (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 003),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 003),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 096),
                                                     (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 096),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 154),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 154),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 995),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 995),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 997),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 997),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 039),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 039),
                                                     (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 992),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 992),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 005),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 005),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 117),
                                                     (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 117),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 048),
                                                     (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 048),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 194),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 194),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 138),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 138),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 111),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 111),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 087),
                                                     (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 087),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 084),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 084),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 090),
                                                     (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 090),
                                                     (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 1001),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 1001),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 132),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 132),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 105),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 105),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 030),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 030),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 075),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 075),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 993),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 993),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 078),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 078),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 033),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 033),
                                                     (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 999),
                                                     (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 999),
                                                     (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 988),
                                                     (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 988),
                                                     (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 007),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 007),
                                                     (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 185),
                                                     (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO kuroro_type (kuroro_id, type_id) VALUES ((SELECT internal_id FROM kuroro WHERE id = 185),
                                                     (SELECT id FROM type WHERE type_name = 'Dark'));
