INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = '???'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Acceleration'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Acidic Flux'), (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Acrid Bite'), (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Aqua Blast'), (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Arcane Knowledge'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Armor Up'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Assault Rush'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Axe Kick'), (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Bark Blast'), (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Bloomburst'), (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Bunker Down'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Burning Lash'), (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Atom'), (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Beam'), (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Bolt'), (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Flame'), (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Gust'), (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Iron'), (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Leaf'), (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Oxide'), (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Pulse'), (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Shadow'), (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Spell'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Charging Wave'), (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Chemical Crash'), (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Corrosive Wave'), (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Crashing Waves'), (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Crosstide'), (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Dark Harvest'), (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Dawngrasp'), (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Degenerate'), (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Depth Attack'), (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Electric Storm'), (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Ferocious Howl'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Ferrous Laser'), (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Fire Blaze'), (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Firebrand'), (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Fist Barrage'), (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Flaming Fists'), (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Flashing Fist'), (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Geologic Burst'), (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Glowing Mists'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Illuminating Beam'), (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Inferno'), (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Introspection'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Iron Slam'), (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Jungle Healing'), (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Lightning Bolt'), (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Luminescence'), (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Maddening Scream'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Magma Shot'), (SELECT id FROM type WHERE type_name = 'Fire'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Mass Abduction'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Meditate'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Meditative Strike'), (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Metal Grinder'), (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Mystic Veil'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Natural Veil'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Nature Protection'), (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Nerve Pulse'), (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Night’s Embrace'), (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Oni Slash'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Otherside Embrace'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Paralysis Wave'), (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Petal Scythe'), (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Provocation'), (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Quicksand Trap'), (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Redirection Sign'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Roundhouse Slam'), (SELECT id FROM type WHERE type_name = 'Combat'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Sandstorm'), (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Seismic Wave'), (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Shade Slash'), (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Shadowblade'), (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Shear Stream'), (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Shield'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Silicon Slashes'), (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Skyfall'), (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Sleep Pollen'), (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Soft Reset'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Soul Contract'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Spirit Beam'), (SELECT id FROM type WHERE type_name = 'Spirit'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Spring'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Steel Blast'), (SELECT id FROM type WHERE type_name = 'Metal'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Strike Conduit'), (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Sulfuric Sting'), (SELECT id FROM type WHERE type_name = 'Corrosion'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Sunblade'), (SELECT id FROM type WHERE type_name = 'Light'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Team Help'), (SELECT id FROM type WHERE type_name = 'Support'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Thicket Thrash'), (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Thunderous Boom'), (SELECT id FROM type WHERE type_name = 'Electric'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Titanic Quake'), (SELECT id FROM type WHERE type_name = 'Earth'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Torrential Blast'), (SELECT id FROM type WHERE type_name = 'Water'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Total Eclipse'), (SELECT id FROM type WHERE type_name = 'Dark'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Untamed Growth'), (SELECT id FROM type WHERE type_name = 'Plant'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Vacuum Slice'), (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Wind Breaker'), (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Wing Frenzy'), (SELECT id FROM type WHERE type_name = 'Wind'));
INSERT INTO move_type (move_id, type_id) VALUES ((SELECT id FROM move WHERE name = 'Zap Razor'), (SELECT id FROM type WHERE type_name = 'Electric'));
